---

name: my-first-action
on: push
jobs:
   first_job:
     runs-on: ubuntu-latest
     steps:
     - name: Welcome message
       run: echo "My first github action"

     - name: List files
       run: ls 
       
     - name: read files
       run: cat README.md   
