---

name: my-first-action
on: push
jobs:
   first_job:
     runs-on: ubuntu-latest
     steps:
     - name: checkout  
       uses: actions/checkout@v4

     - name: Welcome message
       run: |
            echo "My first github action"
            ls -lrta
            cat README.md
            

    #  - name: List files
    #    run: ls 
       
    #  - name: read files
    #    run: cat README.md   
