---
name: Generate ascii workflow 
on: push
jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: list files
      run: ls -lrta  
    - name: Executing shell script
      run: |
           chmod +x
           ./ascii-script.sh
